spring.application.name=fuelbridge-catalog-service
spring.jpa.hibernate.naming.physical-strategy=com.halofuel.fuelbridge.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
fuelbridge.api.url=${FUELBRIDGE_API_URL}
spring.profiles.default=mysql
server.port=${PORT:8080}
